# Matrices

Una $\textbf{matriz}$ es un arreglo de información en filas y columnas, donde una fila es cada una de las líneas horizontales de la matriz y una columna es cada una de las líneas verticales. Una matriz $M$ $n\times m$ tiene $n$ filas y $m$ columnas se denotará ($M_{n\times m}$). Cada elemento de $M$ se denota como $a_{ij}$ donde $a_{ij}\in\mathbb{R}$ es el elemento en la fila $i$ y columna $j$. Si $n=m$ se dir\'a que la matriz es cuadrada. Por otra parte, las matrices donde $n=1$ ($m=1$) se conocen como vectores fila (columna).

$$M=\begin{bmatrix}7&-2\\3&1 \end{bmatrix}.$$
En Python es posible crear matrices de diferentes maneras, la más utilizada es a partir del módulo $\texttt{numpy}$.

In [2]:
import numpy as np

M = np.array([[7,-2],[3,1]])
print(M)

[[ 7 -2]
 [ 3  1]]


In [ ]:
M.shape, M.ndim, M.dtype # Note que a diferencia de las listas, solo se permite un type.

((2, 2), 2, dtype('int64'))

In [ ]:
Ident = np.eye(3)
print(Ident)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Unos = np.ones((3,3))
Unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
Nula = np.zeros([3,3])
Nula

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Operaciones con matrices
Sea $A=(a_{ij})_{m\times n}$, $B=(b_{ij})_{m\times n}$, $C=(c_{ij})_{n\times p}$ y $\alpha\in\mathbb{R}$. Entonces:

* Suma: $A+B= (a_{ij}+b_{ij})_{m\times n}$.
* Multiplicación por escalar: $\alpha A=(\alpha a_{ij})_{m\times n}$.
* Traspuesta: $A^T=A'=(a'_{ij}=a_{ji})_{n\times m}$.
* Multiplicación entre matrices: $A\times C=D_{m\times p}=(d_{ij}=a_{i1}c_{1j}+a_{i2}c_{2j}+\dots+a_{in}c_{nj})_{m\times p}$.

### Ejercicio:

Sea

$$A = \begin{bmatrix} 2&3&4\\ 5&6&7\end{bmatrix}\quad \quad B=\begin{bmatrix}5&-1&9\\4&2&-8\end{bmatrix}\quad\quad C=\begin{bmatrix}4&1&5\\7&9&11\\13&2&1\\-2&7&17\end{bmatrix}$$
Hallar

1. $A+B$
2. $3A$
3. 3A-2B
4. $C'$
5. $C'\cdot C$ o $C'C$


In [ ]:
M1 = np.array([[-3,0],[-2,2]])
M+M1,3*M1, M.dot(M1), np.dot(M,M1), np.transpose(M)

(array([[ 4, -2],
        [ 1,  3]]),
 array([[-9,  0],
        [-6,  6]]),
 array([[-17,  -4],
        [-11,   2]]),
 array([[-17,  -4],
        [-11,   2]]),
 array([[ 7,  3],
        [-2,  1]]))

In [ ]:
M1.dot(M)

array([[-21,   6],
       [ -8,   6]])

## Tipos de matrices

* $A=(a_{ij})_{m\times n}$ es $\textbf{nula}$ si $a_{ij}=0$ para todo $i,j$.
* $A=(a_{ij})_{m\times n}$ es $\textbf{triangular superior}$ si $a_{ij}=0$ para $i>j$.
* $A=(a_{ij})_{m\times n}$ es $\textbf{triangular inferior}$ si $a_{ij}=0$ para $i<j$.
* $A=(a_{ij})_{m\times n}$ es $\textbf{diagonal}$ si $a_{ij}=0$ para $i\neq j$.
* $A=(a_{ij})_{m\times n}$ es $\textbf{escalar}$ si $a_{ij}=0$ para $i\neq j$ y $a_{ii}=k$ con $k\in\mathbb{R}$.
* $A=(a_{ij})_{m\times n}$ es $\textbf{simétrica}$ si $A'=A$.

## Vectores ortogonales

Dos vectores a,b son ortogonales si $a\cdot b=0$.

__Ejemplo:__ Tome $a=(1,0)$ y $b=(0,1)$.

In [3]:
a, b = np.array([1,0]), np.array([0,1])
a.dot(b)

0

## Determinante

El determinante de una matriz es un único escalar asociado con una matriz y tiene las siguientes propiedades

* Al intercambiar dos filas o dos columnas el signo del determinante cambia.
* Al multiplicar una fila por una constante el determinante ser\'a multiplicado por la constante.
* El determinante es lineal en cada fila. Esto es, si define el determinante como $d:\mathbb{R}^{n\times n}\rightarrow\mathbb{R}$, entonces
\begin{equation}
					d(aV1+bW_1,V_2,\dots,V_n)=ad(V_1,V_2,\dots,V_n)+bd(W_1,V_2,\dots,V_n)
\end{equation}

Lo anterior, junto al hecho de que el determinante de la matriz identidad es 1, son suficientes para definir una única función que tome las $n$ columnas de la matriz $A$ y retorne un número real (determinante).

Si $A$ es una matriz de $n\times n$ entonces podemos calcular el determinante de $A$ con
			\begin{equation}
				|A|= a_{i1}A_{i1}+a_{i2}A_{i2}+\dots+a_{in}A_{in}=\sum_{j=1}^na_{ij}A_{ij}.
			\end{equation}
 $A_{ij}$ se conoce como el co-factor del elemento $a_{ij}$. El co-factor es el determinante de la matriz que resulta de eliminar la fila $i$ y la columna $j$.

 \begin{equation}
				A_{ij}=(-1)^{i+j}\begin{bmatrix}
					a_{11}&a_{12}&\dots&a_{1j}&\dots&a_{1n}\\
					a_{21}&a_{22}&\dots&a_{2j}&\dots&a_{2n}\\
					\vdots&\vdots&\vdots&\vdots&\vdots&\vdots\\
					a_{i1}&a_{i2}&\dots&a_{ij}&\dots&a_{in}\\
					\vdots&\vdots&\vdots&\vdots&\vdots&\vdots\\
					{n1}&a_{n2}&\dots&a_{nj}&\dots&a_{nn}
				\end{bmatrix}
\end{equation}

__Ejemplo:__ Sea $A$ es una matriz $2\times2$
		\begin{equation}
			A=\begin{pmatrix}
				a_{11}&a_{12}\\
				a_{21}&a_{22}
			\end{pmatrix}
		\end{equation}
		Entonces
		\begin{equation}
			|A| =a_{11}a_{22}-a_{12}a_{21}
		\end{equation}

### Ejercicio:

Halle el determinante de las siguientes matrices:

\begin{equation}
				A=\begin{pmatrix}
					2&3\\
					5&9
				\end{pmatrix}
			\quad\quad
		B=\begin{pmatrix}
			5&7&12\\
			6&-1&15\\
			6&8&-1
		\end{pmatrix}
	\end{equation}


### Python



In [ ]:
np.linalg.det(M)

13.0

## Inversa de una matriz

Sea $A$ una matriz no singular de dimensión $n$, entonces existe la matriz $A^{-1}$ tal que

$$AA^{-1}=A^{-1}A=I_n$$

In [ ]:
np.linalg.inv(M)

array([[ 0.07692308,  0.15384615],
       [-0.23076923,  0.53846154]])

## Valores y vectores propios

Sea $A=(a_{ij})_{n\times n}$, entonces

* El polinomio característico asociado a la matriz $A$ es $P(\lambda)=|A-\lambda I_n|$.
* La ecuación característica es $P(\lambda)=|A-\lambda I_n|=0$.
* Las soluciones de la ecuación característica son los valores propios asociados a la matriz $A$.
* Si $A$ es una matriz simérica, entonces sus valores propios $\lambda_i\in\mathbb{R}$.
* Los vectores propios son los vectores que resuelven el sistema $A=\lambda I_n$

### Ejemplo:

Hallar los valores y vectores propios de la siguiente matriz.

$$A=\begin{bmatrix} 2&1&1\\2&3&2\\3&3&4\end{bmatrix}$$

### Ejercicio:

Hallar los valores y vectores propios de las siguientes matrices.

$$A=\begin{bmatrix} -1&1&1\\0&-2&0\\1&1&-1\end{bmatrix}\quad \quad B=\begin{bmatrix} 0&1&0\\0&0&1\\2&-5&4\end{bmatrix}$$

In [ ]:
np.linalg.eig(M)

(array([5.73205081, 2.26794919]),
 array([[0.84457417, 0.38930621],
        [0.53543857, 0.92110839]]))

## Formas cuadráticas

Una forma cuadr\'atica en $\mathbb{R}^k$ es la funci\'on de valor real:
			\begin{equation}
				Q(x)=\sum_{i\leq j}a_{ij}x_ix_j.
			\end{equation}
Algunos ejemplos son $f(x)=x^2$, $f(x,y)=x^2+y^2$, $f(x,y)=xy$. Las formas cuadráticas son el tipo de funciones más simples después de las lineales y las condiciones para las técnicas de optimización son expresadas en términos de formas cuadráticas. Por otro lado, una gran parte de los problemas de optimización la función objetivo es una forma cuadrática. (Ej. Optimización de portafolios o Modelos de aprendizaje supervisado como Mínimos Cuadrados Ordinarios).

Una forma cuadr\'atica general puede ser siempre escrita como $x^TAx$. Donde  $A$ es una matriz $n\times n$ y $x$ es un vector de $n$ variables.

__Ejemplo:__
			\begin{equation}
				a_{11}x_1^2+a_{12}x_1x_2+a_{22}x_2^2=\begin{pmatrix}
					x1&x2\end{pmatrix}\begin{pmatrix}
					a_{11}&a_{12}\\0&a_{22}\end{pmatrix}\begin{pmatrix}
					x1\\x2\end{pmatrix}
			\end{equation}
Más aún, existe una única matriz simétrica que representa la misma expresión:
		\begin{equation}
			a_{11}x_1^2+a_{12}x_1x_2+a_{22}x_2^2=\begin{pmatrix}
				x1&x2\end{pmatrix}\begin{pmatrix}
				a_{11}&0.5a_{12}\\0.5a_{12}&a_{22}\end{pmatrix}\begin{pmatrix}
				x1\\x2\end{pmatrix}
		\end{equation}
Conversamente, si $A$ es una matriz simétrica, entonces $x^TAx$ es una forma cuadrática.

Se dice que $Q(x)$ es

* __Definida positiva__ si $\forall \textbf{x}\neq\textbf{0}$ siempre toma valores positivos.

Ejemplo: $x_1^2+x_2^2$.

* __Definida negativa__ si $\forall \textbf{x}\neq\textbf{0}$ siempre toma
valores negativos.

Ejemplo: $-x_1^2-x_2^2$.

* __Semidefinida positiva__ si $\forall \textbf{x}\neq\textbf{0}$ nunca toma valores negativos.

Ejemplo: $(x_1+x_2)^2$.

* __Semidefinida negativa__ si $\forall \textbf{x}\neq\textbf{0}$ nunca toma valores positivos.

Ejemplo: $-(x_1+x_2)^2$.

* __Indefinida__ si piede tomar valores positivos y negativos.

Ejemplo: $x_1^2-x_2^2$.

Siguiendo lo anterior, se asociará la correspondiente matriz cuadrada a la clasificación de la forma cuadrática que conforma. Esto es:

Sea $A$ una matriz $k\times k$ simétrica. Entonces ($\forall \textbf{x}\neq\textbf{0}\in \mathbb{R}^k$) se dice que  

* $A$ es definida negativa si $Q(x)=x^TAx<0$.
* $A$ es semidefinida negativa si $Q(x)=x^TAx\leq0$.
* $A$ es definida positiva si $Q(x)=x^TAx>0$.
* $A$ es semidefinida positiva si $Q(x)=x^TAx\geq0$.
* $A$ es indefinida si ninguna de las anteriores condiciones se cumple.

Sea $A$ una matriz simétrica $n\times n$. Entonces:

* $A$ es definida positiva si y solo si, todos sus valores propios son positivos.
* $A$ es definida negativa si y solo si, todos sus valores porpios son negativos.
* $A$ es semidefinida positiva si y solo si, todos sus valores propios son no negativos.
* $A$ es semidefinida negativa si y solo si, todos sus valores propios son negativos o cero.
* $A$ es indefinida al menos y valor propio positivo y otro negativo.


### Ejercicio:

1. Un departamento de pesca caza del estado proporciona tres timpos de comida a un lago que alberga a tres especies de peces. Cada pez de la especie 1 consume cada semana un primedo de 1 unidad de alimento 1, 1 unidad de alimento 2 y 2 unidades de alimento 3. Cada pez de la especie 2 consume cada semana un promedio de 3 unidades del alimento 1, 4 del 2 y 5 del 3. Para un pez de la especie 3, el promedio semanal de consumo es de 2 unidades del alimento 1, 1 unidad del alimento 2 y 5 unidades del alimento 3. Cada semana se propocionan al lago 25000 unidades del alimento 1, 20000 unidades del alimento 2 y 55000 del 3. Si suponemos que los peces se comen todo el alimento ¿Cuántos peces de cada especie pueden coexistir en el lago? (Entregue al menos una solución).
 > a. ¿Escriba el problema de la forma $Ax=b$.

 > b. Halle el determinante de $A$.

2. Una inversionista le afirma a su corredor de bolsa que todas sus acciones pertenecen a tres compañias: Delta Airlines, Hilton Hotels y McDonald's, y que hace dos días su valor bajó $ \$350$ pero que ayer aumentó $\$600$. El corredor recuerda que hace dos días el precio de las acciones de Delta bajó ¢$1$ por cada una, mientras que las de Hilton bajaron \$1.5, pero que el precio de las acciones de McDonald's subió \$0.5. También recuerda que ayer el precio de las acciones de Delta subió \$1.5 por acción, el de las de Hilton bajó otros \$0.5 por acción y las de McDonald's subieron \$1.0 Demuestre que el el corredor no cuenta con la información suficiente para calcular el número de acciones que posee la inversionista de cada compañia, pero que si ella dice tener 200 acciones de McDonald's el corredor pueda calcular el número de acciones que posee en Delta y en Hilton.

3. Un fabricante de joyería de diseño tiene órdenes por dos anillos, tres pares de aretes, cinco prendedores y un collar. El fabricante estima que le llevará 1 hora de mano de obra hacer un anillo, hora y media hacer un par de aretes, media hora un prendedor y 2 horas para un collar

> a.Exprese las órdenes del fabricante como un vector renglón.

> b. Exprese los requerimientos en horas para los distintos tipos de joyas como un vector columna.

> c.Utilice el producto escalar para hallar el número total de horas que requerirá para terminar las ordenes.